### PR TITLE
Disk perms

### PR DESCRIPTION
**Pull request by leseb**

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test this please

**Comment by guits** [comment]
jenkins test ceph_ansible-jewel-centos7-cluster

**Comment by guits** [comment]
jenkins test ceph_ansible-kraken-centos7-cluster

**Comment by guits** [comment]
jenkins test ceph_ansible-jewel-xenial-cluster

**Comment by guits** [comment]
jenkins test ceph_ansible-kraken-centos7-cluster

**Comment by guits** [comment]
jenkins test ceph_ansible-jewel-centos7-cluster

**Comment by leseb** [comment]
jenkins test ceph_ansible-jewel-centos7-cluster

**Comment by leseb** [comment]
jenkins test ceph_ansible-kraken-centos7-cluster

**Comment by leseb** [comment]
needs a rebase on top of https://github.com/ceph/ceph-docker/pull/622

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
this needs commits from https://github.com/ceph/ceph-docker/pull/616

**Comment by leseb** [comment]
jenkins test this please

**Pull request closed without merging**
