### PR TITLE
Re-enable nfs-ganesha

### PR DESCRIPTION
**Pull request by jprovaznik**

### CODE REVIEW

**Comment by leseb** [comment]
@jprovaznik it's not building on Ubuntu:

```
deb http://download.ceph.com/nfs-ganesha/deb-V2.5-stable/luminous/ xenial main
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:5 http://download.ceph.com/debian-luminous xenial InRelease [8522 B]
Get:6 http://download.ceph.com/debian-luminous xenial/main amd64 Packages [13.4 kB]
Fetched 22.0 kB in 0s (28.5 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
[91mE: Unable to locate package nfs-ganesha
E: Unable to locate package nfs-ganesha-ceph
E: Unable to locate package nfs-ganesha-rgw
```

**Comment by jprovaznik** [comment]
@leseb there was a wrong repo name, much better now

**Comment by leseb** [comment]
@jprovaznik anything else you want to do with this? Or can we go ahead and merge?

**Comment by jprovaznik** [comment]
@leseb it does what I need, if it looks good to you I think we can merge it

**Pull request merged**
