### PR TITLE
fix broken OSD_DIRECTORY mode

### PR DESCRIPTION
**Pull request by dmitryint**

### CODE REVIEW

**Comment by leseb** [comment]
Thanks dmitry for fixing this.  Perhaps we can add runit to base. Since it's not really tight to this container. 

@ulexus? Thoughts?

**Comment by hunter** [comment]
What's the purpose of using runit/my_init over something a little more simple (like forego)?

**Comment by Ulexus** [comment]
Nothing; it's just the tool at hand.  If you have a better runit alternative, I'm pretty sure we are -happy to use it... as long as we are consistent across all of the packages (though the "all" here will _soon_ be "one").

Anyway, @dmitryint is certainly correct; we missed the actual execution of the daemon at start.  I think we can go ahead and merge this, and if @hunter has a better init option, that is most welcome, but it should go in a separate PR.

**Comment by leseb** [comment]
I'm good with that as well, merging :).

**Comment by Ulexus** [comment]
@leseb  I think @hunter is talking about _replacing_ it with a simpler alternative, not so much moving it to outside of `ceph/base`.

**Comment by hunter** [comment]
Sorry, should have been more clear. Just a simpler replacement for myinit and runit. We've used forego successfully in the past which is just a single Go binary+config for running multiple processes.

I'm just working through some code for #34 to make it work with the daemon image. Might take a look at this after I'm done with the confd stuff.

**Comment by Ulexus** [comment]
@hunter I hadn't heard of [forego](https://github.com/ddollar/forego) before (and it's not exactly high in the Google search listings), but yes, that looks like a much cleaner, simpler option.

**Comment by leseb** [comment]
@hunter it was clear :), I was simply wondering despite of what we use that we should put it on ceph/base :). That's it.

**Pull request merged**
