### PR TITLE
Use KV store with any cluster name

### PR DESCRIPTION
**Pull request by JrCs**
* confd create a /etc/ceph/ceph.conf file but for cluser name different
  of 'ceph' the configuration file must be /etc/ceph/$CLUSTER.conf

### CODE REVIEW

**Comment by leseb** [comment]
why do you have to change the filename?

**Comment by JrCs** [comment]
By default ceph use the configuration with the cluster name in it.
Also the entrypoint.sh failed if it doesn't find the right file: [entrypoint.sh#L41](https://github.com/ceph/ceph-docker/blob/master/daemon/entrypoint.sh#L41)

**Comment by leseb** [comment]
Sorry if I'm missing something but why do you go from `/etc/confd/src/ceph.conf.toml.in` to `/etc/confd/conf.d/ceph.conf.toml`

**Comment by JrCs** [comment]
The `/etc/confd/src/ceph.conf.toml.in`is a template that have @CLUSTER@ token.
I use this template as a source to create the `/etc/confd/conf.d/ceph.conf.toml`replacing @CLUSTER@ token with the value of $CLUSTER.

**Comment by leseb** [comment]
Oh I see, makes sense, seems to be the only way to interpret this variable.

**Pull request merged**
