### PR TITLE
Crush location expert and multi cluster support

### LINKED ISSUE #121: Support CRUSH locations
Spawned by discussion from #113 

CRUSH location types [http://ceph.com/docs/master/rados/operations/crush-map/](http://ceph.com/docs/master/rados/operations/crush-map/):
```
type 0 osd
type 1 host
type 2 chassis
type 3 rack
type 4 row
type 5 pdu
type 6 pod
type 7 room
type 8 datacenter
type 9 region
type 10 root
```

I think we should offer a free-form CRUSH_LOCATION for "experts," but we should also offer each of the types explicitly (ex. CRUSH_RACK), whose purpose and use should be more easily-grasped, though such may be more verbose.

### PR DESCRIPTION
**Pull request by leseb**
Fixes #121 and more.

### CODE REVIEW

**Comment by Ulexus** [comment]
The PR description is a bit misleading, since most of this if actually multi-cluster stuff, but it looks good to me.

**Comment by Ulexus** [comment]
Also, the `CEPH_OPTS` is a great idea.

**Comment by leseb** [comment]
You're right, I'll test this tomorrow, just to make sure I haven't broke anything.

**Comment by Ulexus** [comment]
I do think it should be overridable, though... same as the others at the top of the file; set the default, allowing users to override it, should they wish.

**Comment by Ulexus** [comment]
Fixes #121

**Comment by leseb** [comment]
I think it's a bit risky to let users modify the behaviour of the entrypoint as this can completely mess up the bootstrap of a container.
Moreover I can't think of anything that the users would wish to modify. Can you?

**Comment by Ulexus** [comment]
I have no idea; I don't have any need to do so, but I can certainly see that it might theoretically be useful for something.  On the other hand, people who want that much control can just use base and handle everything themselves.  You're probably right.

**Comment by leseb** [comment]
Was testing this and everything was working accept the MDS.
The MDS will be fixed by #127 

Merging this work first.

**Pull request merged**
