### PR TITLE
Clean up tools README

### PR DESCRIPTION
**Pull request by thecanadianbaker**
Added backtick for code highlighting
Added clarified directions on running from container

### CODE REVIEW

**Comment by Ulexus** [comment]
I believe this should refer to `ceph/base` instead of `ceph/tools`.  @hookenz ?

**Comment by Ulexus** [comment]
Oh, I see.  This is an installation container for the binaries in question.  There is a Dockerfile also in that directory.

@hookenz let's change the name to `ceph/install-utils` or something a bit more descriptive of what the container actually does.  Then I can add it to the Docker Hub repository.

**Comment by thecanadianbaker** [comment]
I will hop on that. Is there any reason not to include RBD in the utils as well?

**Comment by Ulexus** [comment]
None of which I am aware, no.

**Comment by hookenz** [comment]
@Ulexus - Thanks for that.  Sorry I haven't contributed for quite a long time.  We're unfortunately no longer maintaining our own hardware and are moving to Amazon so I'm not using ceph anymore.  But I'm still interested in ceph, it's a fantastic storage platform.

**Pull request closed without merging**
