### PR TITLE
bash refactor for shellcheck compliance

### PR DESCRIPTION
**Pull request by leseb**

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test ceph_ansible-kraken-centos7_cluster

**Comment by leseb** [comment]
jenkins test ceph_ansible-kraken-centos7_cluster

**Comment by leseb** [comment]
Without https://github.com/ceph/ceph-build/pull/713 CI 'for sloppy bash' will never be happy :)

**Comment by leseb** [comment]
jenkins test this please

**Comment by guits** [comment]
jenkins test ceph_ansible-jewel-xenial_cluster

**Comment by guits** [comment]
jenkins test ceph_ansible-jewel-centos7_cluster

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test for sloppy bash

**Comment by leseb** [comment]
jenkins lint

**Comment by leseb** [comment]
jenkins lint

**Comment by leseb** [comment]
jenkins lint

**Comment by leseb** [comment]
jenkins lint

**Comment by leseb** [comment]
awesome! jenkins lint works! I need to rework so issues.

**Comment by leseb** [comment]
jenkins test ceph_ansible-kraken-centos7-cluster

**Comment by leseb** [comment]
jenkins test ceph_ansible-jewel-centos7-cluster

**Comment by leseb** [comment]
jenkins test ceph_ansible-kraken-xenial-cluster

**Comment by leseb** [comment]
jenkins test ceph_ansible-luminous-centos7-cluster

**Comment by leseb** [comment]
jenkins test ceph_ansible-jewel-centos7-cluster

**Comment by leseb** [comment]
jenkins test ceph_ansible-jewel-centos7-dedicated_journal

**Comment by guits** [comment]
jenkins test ceph_ansible-jewel-centos7-dedicated_journal

**Comment by guits** [comment]
jenkins test ceph_ansible-jewel-centos7-dedicated_journal

**Comment by guits** [comment]
jenkins test ceph_ansible-kraken-centos7-dedicated_journal

**Comment by guits** [comment]
jenkins test ceph_ansible-kraken-xenial-cluster

**Comment by guits** [comment]
jenkins test ceph_ansible-kraken-centos7-dedicated_journal

**Comment by guits** [comment]
jenkins test ceph_ansible-kraken-centos7-dedicated_journal

**Comment by guits** [comment]
jenkins test ceph_ansible-kraken-centos7-dedicated_journal

**Comment by leseb** [comment]
jenkins test ceph_ansible-jewel-centos7-dedicated_journal

**Comment by leseb** [comment]
jenkins test ceph_ansible-kraken-centos7-dedicated_journal

**Comment by leseb** [comment]
jenkins test ceph_ansible-kraken-xenial-cluster

**Comment by leseb** [comment]
jenkins test ceph_ansible-jewel-centos7-dedicated_journal

**Comment by leseb** [comment]
jenkins test ceph_ansible-kraken-centos7-dedicated_journal

**Comment by leseb** [comment]
The CI is experiencing the race condition again.. merging anyway.

**Pull request merged**
