### PR TITLE
bluestore osd_disk_activate partition

### LINKED ISSUE #711: bluestore on /dev/loop0 device osd_disk_activate use wrong partition
Hello,
I just tried to run an osd with bluestore on a virtual disk at /dev/loop0 and osd_disk_activate use wrong partition.

ceph-disk prepare created partition like /dev/loop0p1, /dev/loop0p3 ... 
but some partitions are partially hard coded in osd_disk_activate to use  /dev/loop01 and  /dev/loop03 and fail.
```
DATA_UUID=$(get_part_uuid "${OSD_DEVICE}"1)
...
LOCKBOX_UUID=$(get_part_uuid "${OSD_DEVICE}"3 || true)
```
also the following commands fail for bluestore
```
JOURNAL_PART=$(ceph-disk list "${OSD_DEVICE}" | awk '/ceph journal/ {print $1}') # This is privileged container so 'ceph-disk list' works
JOURNAL_UUID=$(get_part_uuid "${JOURNAL_PART}")
```

### PR DESCRIPTION
**Pull request by osixia**
fixes #711

### CODE REVIEW

**Comment by guits** [comment]
sorry, it has been already fixed by #714

**Comment by osixia** [comment]
i think get_part_uuid **"${OSD_DEVICE}"3** and **get_part_uuid "${OSD_DEVICE}"1** will still fail for device on /dev/loop0 for example partition are: /dev/loop0p3 and /dev/loop0p3

**Comment by guits** [comment]
@osixia can you make a new PR for this specific fix?

**Comment by osixia** [comment]
sure :)

**Pull request closed without merging**
