### PR TITLE
MON_IP to use container private ip when using containers network

### PR DESCRIPTION
**Pull request by isserrano**

### CODE REVIEW

**Comment by Ulexus** [comment]
That looks pretty reasonable, thanks.

I'd like to know, though, under what circumstances this actually works.  I can see using an overlay network (à la flannel) to get away from `--net=host`, but all the testing I've ever done relies on monitors (and OSDs) not changing their IPs.  Otherwise, you end up with consensus problem.  How does this use-case avoid that problem?

**Comment by leseb** [comment]
+1 last time I tried putting monitors on Docker they were complaining about the NAT.

**Comment by isserrano** [comment]
The host where the container is will have a fixed ip, and is the one I will
use for the clients and the osd connecting to the monitors.

**Comment by Ulexus** [comment]
I'm still failing to see how this actually works.  The mon will be thinking it is a different IP than it is.  Are you saying you have this in operation?

**Comment by isserrano** [comment]
No. I am building a new cluster and I would like to use containers, I would
like to use nat for the monitors inside the container, that is why  I am
doing that change.

**Comment by Ulexus** [comment]
I'm pretty sure no one has a functional cluster with NAT'd monitors.  If you get this working, though, I'd be more than interested.

**Comment by leseb** [comment]
+1 NAT'd monitors can't work...

**Comment by Ulexus** [comment]
I'm going to close this for now, @isserrano .  If you have differing results, please reopen it.

**Pull request closed without merging**
