### PR TITLE
tests: split os-type and scenario factors

### PR DESCRIPTION
**Pull request by andrewschoen**
This allows us to add new testing scenarios without repeating the
configuration needed for different operating systems.

Signed-off-by: Andrew Schoen <aschoen@redhat.com>

### CODE REVIEW

**Comment by andrewschoen** [comment]
corresponding ceph-build PR https://github.com/ceph/ceph-build/pull/717

**Comment by andrewschoen** [comment]
jenkins test this please

**Comment by alfredodeza** [comment]
jenkins test this please

**Comment by andrewschoen** [comment]
jenkins test this please

**Comment by andrewschoen** [comment]
The scenarios with an underscore (xenial_cluster and centos7_cluster) no longer exist in jenkins so the failures can be ignored here.

**Comment by andrewschoen** [comment]
It seems we need more work in ceph-ansible to skip ceph-mgr related tasks for a jewel container.

```
TASK [ceph-mgr : copy mgr key to /var/lib/ceph/mgr/test-ceph-mgr0/keyring] *****
task path: /home/jenkins-build/build/workspace/ceph-docker-prs-ceph_ansible-jewel-centos7-cluster/ceph-ansible/roles/ceph-mgr/tasks/docker/fetch_configs.yml:30
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..

This feature will be removed in version 2.4. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
failed: [mgr0] (item={'failed_when_result': False, 'invocation': {u'module_args': {u'get_md5': True, u'path': u'/home/jenkins-build/build/workspace/ceph-docker-prs-ceph_ansible-jewel-centos7-cluster/ceph-ansible/tests/functional/centos/7/docker-cluster/fetch/docker_mon_files//etc/ceph/test.conf', u'get_checksum': True, u'mime': False, u'follow': False, u'checksum_algorithm': u'sha1'}, 'module_name': u'stat'}, 'item': u'/etc/ceph/test.conf', 'failed': False, '_ansible_item_result': True, '_ansible_delegated_vars': {'ansible_host': u'localhost'}, '_ansible_no_log': False, u'stat': {u'size': 1128, u'ischr': False, u'xusr': False, u'atime': 1494951442.25412, u'md5': u'537ad8aa1fb4956de86842c995bfb475', u'gid': 118, u'dev': 2049, u'isblk': False, u'inode': 1034519, u'islnk': False, u'mode': u'0664', u'nlink': 1, u'xoth': False, u'readable': True, u'wgrp': True, u'xgrp': False, u'executable': False, u'isdir': False, u'isgid': False, u'path': u'/home/jenkins-build/build/workspace/ceph-docker-prs-ceph_ansible-jewel-centos7-cluster/ceph-ansible/tests/functional/centos/7/docker-cluster/fetch/docker_mon_files//etc/ceph/test.conf', u'issock': False, u'mtime': 1494951372.9891427, u'isfifo': False, u'woth': False, u'isreg': True, u'checksum': u'8cfb7326562faa9bce9d4bfe565681fd282d6d0f', u'ctime': 1494951372.9891427, u'wusr': True, u'rusr': True, u'gr_name': u'docker', u'rgrp': True, u'roth': True, u'isuid': False, u'exists': True, u'uid': 1001, u'pw_name': u'jenkins-build', u'writeable': True}, '_ansible_parsed': True, u'changed': False}) => {
    "changed": false, 
    "cmd": [
        "cp", 
        "/etc/ceph/test.mgr.ceph-mgr0.keyring", 
        "/var/lib/ceph/mgr/test-ceph-mgr0/keyring"
    ], 
    "delta": "0:00:00.003665", 
    "end": "2017-05-16 16:27:49.513115", 
    "failed": true, 
    "item": {
        "changed": false, 
        "failed": false, 
        "failed_when_result": false, 
        "invocation": {
            "module_args": {
                "checksum_algorithm": "sha1", 
                "follow": false, 
                "get_checksum": true, 
                "get_md5": true, 
                "mime": false, 
                "path": "/home/jenkins-build/build/workspace/ceph-docker-prs-ceph_ansible-jewel-centos7-cluster/ceph-ansible/tests/functional/centos/7/docker-cluster/fetch/docker_mon_files//etc/ceph/test.conf"
            }, 
            "module_name": "stat"
        }, 
        "item": "/etc/ceph/test.conf", 
        "stat": {
            "atime": 1494951442.25412, 
            "checksum": "8cfb7326562faa9bce9d4bfe565681fd282d6d0f", 
            "ctime": 1494951372.9891427, 
            "dev": 2049, 
            "executable": false, 
            "exists": true, 
            "gid": 118, 
            "gr_name": "docker", 
            "inode": 1034519, 
            "isblk": false, 
            "ischr": false, 
            "isdir": false, 
            "isfifo": false, 
            "isgid": false, 
            "islnk": false, 
            "isreg": true, 
            "issock": false, 
            "isuid": false, 
            "md5": "537ad8aa1fb4956de86842c995bfb475", 
            "mode": "0664", 
            "mtime": 1494951372.9891427, 
            "nlink": 1, 
            "path": "/home/jenkins-build/build/workspace/ceph-docker-prs-ceph_ansible-jewel-centos7-cluster/ceph-ansible/tests/functional/centos/7/docker-cluster/fetch/docker_mon_files//etc/ceph/test.conf", 
            "pw_name": "jenkins-build", 
            "readable": true, 
            "rgrp": true, 
            "roth": true, 
            "rusr": true, 
            "size": 1128, 
            "uid": 1001, 
            "wgrp": true, 
            "woth": false, 
            "writeable": true, 
            "wusr": true, 
            "xgrp": false, 
            "xoth": false, 
            "xusr": false
        }
    }, 
    "rc": 1, 
    "start": "2017-05-16 16:27:49.509450", 
    "warnings": []
}

STDERR:

cp: cannot stat ‘/etc/ceph/test.mgr.ceph-mgr0.keyring’: No such file or directory
skipping: [mgr0] => (item={'failed_when_result': False, 'invocation': {u'module_args': {u'get_md5': True, u'path': u'/home/jenkins-build/build/workspace/ceph-docker-prs-ceph_ansible-jewel-centos7-cluster/ceph-ansible/tests/functional/centos/7/docker-cluster/fetch/docker_mon_files//etc/ceph/test.mgr.ceph-mgr0.keyring', u'get_checksum': True, u'mime': False, u'follow': False, u'checksum_algorithm': u'sha1'}, 'module_name': u'stat'}, 'item': u'/etc/ceph/test.mgr.ceph-mgr0.keyring', 'failed': False, '_ansible_item_result': True, '_ansible_delegated_vars': {'ansible_host': u'localhost'}, '_ansible_no_log': False, u'stat': {u'exists': False}, '_ansible_parsed': True, u'changed': False})  => {
    "changed": false, 
    "item": {
        "changed": false, 
        "failed": false, 
        "failed_when_result": false, 
        "invocation": {
            "module_args": {
                "checksum_algorithm": "sha1", 
                "follow": false, 
                "get_checksum": true, 
                "get_md5": true, 
                "mime": false, 
                "path": "/home/jenkins-build/build/workspace/ceph-docker-prs-ceph_ansible-jewel-centos7-cluster/ceph-ansible/tests/functional/centos/7/docker-cluster/fetch/docker_mon_files//etc/ceph/test.mgr.ceph-mgr0.keyring"
            }, 
            "module_name": "stat"
        }, 
        "item": "/etc/ceph/test.mgr.ceph-mgr0.keyring", 
        "stat": {
            "exists": false
        }
    }, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}
```

We don't see this in ceph-ansible CI tests because the CI there passed ``ceph_stable_release=jewel`` for jewel tests which makes this conditional fail: https://github.com/ceph/ceph-ansible/blob/master/site-docker.yml.sample#L58

A quick fix would be to have the ceph-docker CI tests also pass ``ceph_stable_release=$CEPH_RELEASE`` here as well.

**Comment by andrewschoen** [comment]
jenkins test ceph_ansible-jewel-xenial-cluster

**Comment by leseb** [comment]
@andrewschoen is there anything else to do? You mentioned doing stuff in ceph-ansible in your last comment.

**Comment by andrewschoen** [comment]
@leseb no, I was able to handle it all within ceph-docker.

**Pull request merged**
