### PR TITLE
Use Infernalis

### PR DESCRIPTION
**Pull request by leseb**
Use Ceph's last stable version.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by Ulexus** [comment]
Cheer!  We will need to fork the new branch on Docker Hub, and I believe we were discussing removing the various discrete daemons in favour of the common ceph/daemon container.  Do you still want to do that now, or wait until Jewel?  I would prefer to not keep the duplication of effort, personally.

**Comment by leseb** [comment]
Well given that Hammer was the new LTS, we could have done that earlier. I believe we can go ahead with #94. The Infernalis release comes with a new way to run the ceph daemons (using a ceph user). So we actually need more than this simple commit. I'll amend or add more commits to this PR, so do not merge it yet :).

**Comment by Ulexus** [comment]
Sounds good.  I'm over in Barcelona for the week, so I'm a bit hamstrung at the moment, anyway.

**Comment by leseb** [comment]
I assume you're at the Docker Con, so enjoy!

**Comment by Ulexus** [comment]
Indeed, and I'll be speaking at Distributed Matters, as well, this weekend.

On Wed, 18 Nov 2015, 00:05 Leseb <notifications@github.com> wrote:

> I assume you're at the Docker Con, so enjoy!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph-docker/pull/166#issuecomment-157538642>.
>
-- 
Seán C McCord
CyCore Systems, Inc
+1 888 240 0308

**Comment by leseb** [comment]
Updated the PR, I need to test all of this now. :)

**Comment by leseb** [comment]
Closing this in favour of #167 since it has the proper branch name...

**Pull request closed without merging**
