### PR TITLE
Use the latest stable version of Ceph

### PR DESCRIPTION
**Pull request by leseb**
Moving away from Firefly and use Giant instead.

Fixes: #31 
Signed-off-by: Sébastien Han <sebastien.han@enovance.com>

### CODE REVIEW

**Comment by leseb** [comment]
@Ulexus Not sure how we can properly create a tag for firefly...

**Comment by Ulexus** [comment]
We now have Docker tags for `firefly` and `giant` (as per #31 ), and the modifications to `ceph/base` seem to work as expected for the `giant` release.

My only question is with respect to the upgrade.  Is it safe for people using the `latest` tag to simply pull fresh containers and run them, or does there need to be additional checking or instructions involved for the upgrade.  

Since I'm one of the users of the `latest` tag, I'd really hate to destroy my ceph cluster by merging this PR. ;)

**Comment by leseb** [comment]
We should probably add a warning, just to remember users to always use tags (and ceph version) while pulling an image form the hub.
For the upgrade you might to follow a sequence.

**Comment by Ulexus** [comment]
Is there any way to query the versions of the other daemons in the Ceph cluster before running the component?  That is, can we have an OSD container check that the MONs are upgraded before running itself?  Is that even a good or necessary action?

The order appears to be fairly simple for the actual upgrade, though:
 1.  Upgrade each monitor
 2.  Upgrade each OSD
 3.  Upgrade each other daemon (MDS, RADOSGW)
 4.  Upgrade the utilities (rbd,rados,etc.)

**Comment by Ulexus** [comment]
The warning is good.  The only problem is that we _didn't_ have tagging before yesterday, so everyone was necessarily using `:latest`.

The plus side there is that according to Docker Hub, there have only been a couple hundred downloads of `ceph/osd`, and fewer still `ceph/mon`.  For all I know, that could just be me (though that is probably not the case).  In any case, there should not be very many clusters affected, if out-of-order upgrading causes issues.  Of course, to those few...  It would be nice if we had a way to issue email notices to container users, but that's not going to happen, I'm afraid.

**Comment by leseb** [comment]
To check the mon version you can:

```ceph daemon mon.$(hostname) version```

However this needs to be run inside the container since this talks to the socket.
For OSDs you can:

```ceph osd metadata $osd_id```

**Comment by leseb** [comment]
Agree on the few users that might be affected, I don't see any good way to email current users.
I believe we will have to merge that like this :(

**Comment by Ulexus** [comment]
In that case, I guess we merge away

**Pull request merged**
