### PR TITLE
Docker Registry

### PR DESCRIPTION
**Pull request by lorieri**
local docker repository that saves images on Rados gateway

### CODE REVIEW

**Comment by leseb** [comment]
can we move this on the 'ceph' organisation on docker hub?

**Comment by lorieri** [comment]
Hi, it was a PR I did for docker-registry, since it was accepted I put the original repository.
But now I get the what you mean, I will close the PR and make it looks like the others.

**Comment by leseb** [comment]
Awesome thanks!

**Comment by Ulexus** [comment]
Yes, I've been hoping to see a rados-backed docker registry.  That would be quite nice, thanks!

**Pull request closed without merging**
