### PR TITLE
Update default etcd port

### PR DESCRIPTION
**Pull request by JrCs**
The official etcd client port is 2379 and it is officialy registered at the Internet Assigned Numbers Authority (IANA).

### CODE REVIEW

**Comment by guits** [comment]
jenkins test this please

**Comment by guits** [comment]
@JrCs what about other releases?
```
$ git grep 4001
ceph-releases/hammer/ubuntu/14.04/daemon/entrypoint.sh:33:: ${KV_PORT:=4001} # PORT 8500 for Consul
ceph-releases/infernalis/ubuntu/14.04/daemon/entrypoint.sh:33:: ${KV_PORT:=4001} # PORT 8500 for Consul
ceph-releases/jewel/ubuntu/14.04/daemon/README.md:49:-e KV_PORT=4001 \
ceph-releases/jewel/ubuntu/14.04/daemon/variables_entrypoint.sh:58:: "${KV_PORT:=4001}"
ceph-releases/kraken/ubuntu/16.04/daemon/README.md:49:-e KV_PORT=4001 \
ceph-releases/kraken/ubuntu/16.04/daemon/variables_entrypoint.sh:58:: "${KV_PORT:=4001}"
ceph-releases/luminous/ubuntu/16.04/daemon/README.md:49:-e KV_PORT=4001 \
ceph-releases/luminous/ubuntu/16.04/daemon/variables_entrypoint.sh:58:: "${KV_PORT:=4001}"
```

**Comment by JrCs** [comment]
Done on other releases

**Comment by JrCs** [comment]
jenkins test this please

**Comment by guits** [comment]
jenkins test ceph_ansible-jewel-centos7-cluster

**Pull request merged**
