### PR TITLE
since ceph-disk activate already starts ceph-osd, don't rerun it; just wait till it exits

### PR DESCRIPTION
**Pull request by rootfs**
@leseb

### CODE REVIEW

**Comment by leseb** [comment]
@rootfs we had a similar fix for the centos branch, what do you think about it? https://github.com/ceph/ceph-docker/pull/188/files

**Comment by rootfs** [comment]
that's brutal, but works :)

**Comment by leseb** [comment]
Yes so we don't have to wait and using mark_init none helps with containers too.

**Comment by leseb** [comment]
If you are ok, do you mind using the same code so we keep things consistent? :)

**Comment by rootfs** [comment]
done, thanks.

**Comment by leseb** [comment]
@rootfs thanks! @Ulexus any objection?

**Comment by Ulexus** [comment]
I agree with @rootfs that looks brutal... I don't know the problem, but that seems aggressive

**Comment by rootfs** [comment]
@Ulexus. The problem is that `ceph-disk activate`  spawns `ceph-osd`. So when `entrypoint.sh` continues to `exec ceph-osd`, `ceph-osd` just fails and complains there is another osd daemon running. 

So the solution space left for us is either kill the ceph-osd that `ceph-disk activate` spawns, or keep that osd daemon and watch it.

**Comment by Ulexus** [comment]
Yeah, I see.  I wish I had a better option.  We could monitor that process and exit coincidentally, but that doesn't really seem any better.  `ceph-disk` will not will any accolades from me, but if this is what it takes and if the `ceph-osd` process dies gracefully, then we might as well do it.  (There should have been plenty of Eeyore tones in there, if you didn't pick them up.)

**Comment by leseb** [comment]
@Ulexus so let's go with the "brutal" way? :)

**Comment by Ulexus** [comment]
Hah.  Yes, let's! :)

**Comment by rootfs** [comment]
sorry late to the part. Yes, `killall` is brutal. I just found a couple of issues
- `killall` is not installed by default on centos container (might be the same for ubuntu)
- worse, `killall -9 -w` also kills other osd.

So the watch and wait (the first commit) seems a nicer/safer way to me.

**Comment by leseb** [comment]
Oops... yes  indeed, let me revert this change.

**Comment by leseb** [comment]
@rootfs do you mind re-submitting your patch? :) Thanks!

**Comment by rootfs** [comment]
okie dokie

**Pull request merged**
