### PR TITLE
Some optimizations for rbd-lock/rbd-unlock containers

### PR DESCRIPTION
**Pull request by dmitryint**

### CODE REVIEW

**Comment by leseb** [comment]
Nice refactor thanks! @dmitryint. Can you also update the README to reflect this change?
We need to document the new ETCDCTL_PEERS variable.

**Comment by dmitryint** [comment]
done

**Comment by leseb** [comment]
Thanks @dmitryint

**Comment by Ulexus** [comment]
Indeed, that's much better, thanks!

**Pull request merged**
