### PR TITLE
alter error of path

### PR DESCRIPTION
**Pull request by yxwzaxns**

### CODE REVIEW

**Comment by leseb** [comment]
@yxwzaxns why do you remove `ARG`, this is supposed to fix Travis, but this might bring issues too.

About the other change, it'll be nice if you could apply it to other distros and ceph versions too, I know this is not ideal. I'm trying to find a better way for that.

**Comment by yxwzaxns** [comment]
are you change the docker version to 1.11.2? the version 1.8.0 can't  support ARG

**Comment by yxwzaxns** [comment]
I can't solve the problem of Travis

**Comment by leseb** [comment]
@yxwzaxns yeah I just upgraded the docker version, now I'm hitting another issue that I'm trying to solve. Stay tuned :)

**Comment by yxwzaxns** [comment]
hi,what time do you merge the pull request

**Comment by leseb** [comment]
Sorry for the delay, I'll merge this today, I just need to take a decision regarding Travis CI.
I'll fix this today.

**Comment by leseb** [comment]
@JrCs what do you think about this?

**Comment by leseb** [comment]
@yxwzaxns please remove the CI skip

**Comment by yxwzaxns** [comment]
I need remove CI skip now?

**Comment by JrCs** [comment]
@leseb LGTM but i prefer to separate template files and config files in distinct directories (this is why i have create an `src` directory for the templates).

**Pull request merged**
