### PR TITLE
add a note on the new CI testing in Jenkins

### PR DESCRIPTION
**Pull request by alfredodeza**
Signed-off-by: Alfredo Deza <adeza@redhat.com>

### CODE REVIEW

**Comment by alfredodeza** [comment]
hey @leseb this looks like a path is wrong somewhere, mind taking a look here? (see 'Details' link)

    + sudo /home/jenkins-build/build/workspace/ceph-docker-pull-requests/ceph-docker/travis-builds/build_imgs.sh
    + copy_dirs
    + [[ ! -d daemon ]]
    + build_base_img
    + pushd base
    /mnt/jenkins/workspace/ceph-docker-pull-requests/base /mnt/jenkins/workspace/ceph-docker-pull-requests
    + docker build -t base .
    unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /mnt/jenkins/workspace/ceph-docker-pull-requests/base/Dockerfile: no such file or directory
    Build step 'Execute shell' marked build as failure

**Comment by alfredodeza** [comment]
test this please

**Comment by alfredodeza** [comment]
test this please

**Comment by alfredodeza** [comment]
I think these failures are in a good spot now for reviewing :)

**Comment by leseb** [comment]
@alfredodeza looks like there is one line that will always fail and this is normal: https://github.com/ceph/ceph-docker/blob/master/.travis.yml#L50-L52
Search for this error in the logs:

```
+ sudo docker exec ceph-mon ceph -s
Error response from daemon: Container 8767a07cc56b936d2c2178e43de34a4a472fe8ec580498156a0ad25077048658 is not running
```

The `ceph-mon` was purge so this is normal, please remove this call. I'll remove that from travis as well.

**Comment by alfredodeza** [comment]
test this please

**Comment by alfredodeza** [comment]
test this please

**Comment by alfredodeza** [comment]
test this please

**Pull request merged**
