### PR TITLE
Centos

### PR DESCRIPTION
**Pull request by leseb**

### CODE REVIEW

**Comment by Ulexus** [comment]
@leseb  You don't intend for this to be merged into the `master` branch, do you?  This is for the `centos` branch... as already applied?

**Comment by leseb** [comment]
@Ulexus Oops, actually I'd like to do the other way around. Is it possible to merge master's content into the centos branch?

**Comment by Ulexus** [comment]
There is probably a simpler way, but this sequence is basically what I do:
```
git checkout master
git pull --rebase
git checkout centos
git merge master
git push
```

**Comment by Ulexus** [comment]
`git merge` is smart enough to keep the centos-branch changes.  If they conflict, it will halt the merge, created noted source files, and give you instructions to resolve the conflict.  You should have very few conflicts, though.

**Comment by leseb** [comment]
Indeed I had very few conflicts, thanks @Ulexus!
Centos branch is up to date now :).

**Comment by Ulexus** [comment]
Excellent!  I've been _really_ happy with git's branch maintenance after too many years of subversion.

**Pull request closed without merging**
