### PR TITLE
confd requires http:// prefix for etcd

### PR DESCRIPTION
**Pull request by MichaelSp**

### CODE REVIEW

**Comment by leseb** [comment]
Since when is it needed?

**Comment by MichaelSp** [comment]
I don't know. All I know is, that without the "http://" prefix it doesn't work for me...

**Comment by leseb** [comment]
I haven't used this recently, @Ulexus any idea? Did we bump the confd version?

**Comment by leseb** [comment]
@MichaelSp do you mind rebasing your patch and do your modifications in `ceph-releases/jewel/ubuntu/14.04`? Thanks!

**Comment by MichaelSp** [comment]
If the files "don't exist" why don't you remove them? This is version control. You can have them back any time you want. This just confuses others and me.
I'll try to find to to rebase...

**Comment by leseb** [comment]
@MichaelSp please read the recent changes on the README.

**Comment by einyx** [comment]
why this hasn't been merged?

**Comment by leseb** [comment]
@einyx because it needs a rebase, @MichaelSp doesn't have time, @einyx you can take over if you want. Please update `ceph-releases/jewel/ubuntu/14.04/daemon/config.kv.sh`.

**Comment by damoon** [comment]
saw this to late and fixed the same thing. also fixed httpS for etcd https://github.com/ceph/ceph-docker/pull/327

**Pull request closed without merging**
