### PR TITLE
Add TLS support for key-value store.

### PR DESCRIPTION
**Pull request by clinta**
This change allows connecting to a KV store over TLS by setting the `KV_CA_CERT`, `KV_CLIENT_CERT` and `KV_CLIENT_KEY` variables.

### CODE REVIEW

**Comment by leseb** [comment]
@clinta I fixed the issue with Travis, can you remove the commit for Travis?

**Comment by clinta** [comment]
Removed Travis fix and rebased.

**Comment by clinta** [comment]
Looking closer, I'm missing these options in calls confd.

**Comment by clinta** [comment]
This now has TLS options for all the calls to confd. I'm working on testing it now.

**Comment by clinta** [comment]
This is working in my environment now. I had to upgrade kviator to support TLS and add an additional option to confd to set the scheme to https.

**Comment by leseb** [comment]
Thanks!

**Pull request merged**
