### PR TITLE
Add RGW_REGION and RGW_ZONE variables

### PR DESCRIPTION
**Pull request by JrCs**
Add new variables to help creating multi-sites rados gateways.

### CODE REVIEW

**Comment by leseb** [comment]
New PR should go in the ceph-releases directory

**Comment by yehudasa** [comment]
@JrCs 'region' is an obsolete term, should use 'zonegroup' instead

**Comment by JrCs** [comment]
@yehudasa i know that `region`is an obsolete term, but for the radosgw-admin command the option is `--rgw-region`

**Comment by yehudasa** [comment]
@JrCs can now use --rgw-zonegroup instead

**Comment by JrCs** [comment]
@yehudasa yes i will remake my PR

**Pull request closed without merging**
