### PR TITLE
split osd disk to disk prepare and disk activate

### PR DESCRIPTION
**Pull request by rootfs**
@leseb

### CODE REVIEW

**Comment by leseb** [comment]
@rootfs even though we discussed that on irc, a little commit message is welcome :)

**Comment by rootfs** [comment]
The idea is that when prepare and activate are split, it is possible to prepare the osd first, leaving osd activate to systemd. Then systemd activates osd without having to prepare again.

**Comment by leseb** [comment]
Thanks @rootfs 
I'm good with this one, @Ulexus?

**Comment by Ulexus** [comment]
I like this, yes.  It's a good way to split out the process so that fixes (like permissions) can be injected.  LGTM.

**Comment by Ulexus** [comment]
It should probably have some documentation added to the README also.

**Comment by rootfs** [comment]
@Ulexus thanks, just updated `README.md`

**Comment by Ulexus** [comment]
Thanks, @rootfs

**Pull request merged**
