### PR TITLE
Fix improper following of device symlinks

### LINKED ISSUE #750: Device symlinks are improperly followed
In the luminous scripts, there is code to follow device symlinks. I have specified `/dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0` as my disk, and I am getting errors. From running the script with `bash +x` specified, I can see that that the paths aren't being traversed properly.

### Relevant output of `bash +x entrypoint.sh`:
```
...
++ dev_part /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0 2
++ local osd_device=/dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0
++ local osd_partition=2
++ [[ -L /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0 ]]
++ local actual_device
+++ readlink -f /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0
++ actual_device=/dev/sda
++ local bn
+++ basename /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0
++ bn=pci-0000:00:04.0-scsi-0:0:0:0
++ [[ a == [0-9] ]]
++ local desired_partition=/dev/sda2
++ local symdir
+++ dirname /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0
++ symdir=/dev/disk/by-path
++ local link=
++ local pfxlen=0
++ for option in '${symdir}*'
++ [[ -e /dev/disk/by-path ]]
+++ readlink -f /dev/disk/by-path//dev/disk/by-path
++ [[ '' == \/\d\e\v\/\s\d\a\2 ]]
++ [[ 0 -eq 0 ]]
++ log 'Could not locate appropriate symlink for partition 2 of /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0'
++ '[' -z 'Could not locate appropriate symlink for partition 2 of /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0' ']'
++ local timestamp
+++ date '+%F %T'
++ timestamp='2017-08-18 20:34:04'
++ echo '2017-08-18 20:34:04  entrypoint.sh: Could not locate appropriate symlink for partition 2 of /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0'
2017-08-18 20:34:04  entrypoint.sh: Could not locate appropriate symlink for partition 2 of /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0
++ return 0
++ exit 1
+ wait_for_file ''
+ timeout 10 bash -c 'while [ ! -e  ]; do echo '\''Waiting for  to show up'\'' && sleep 1 ; done'
++ dev_part /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0 2
++ local osd_device=/dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0
++ local osd_partition=2
++ [[ -L /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0 ]]
++ local actual_device
+++ readlink -f /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0
++ actual_device=/dev/sda
++ local bn
+++ basename /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0
++ bn=pci-0000:00:04.0-scsi-0:0:0:0
++ [[ a == [0-9] ]]
++ local desired_partition=/dev/sda2
++ local symdir
+++ dirname /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0
++ symdir=/dev/disk/by-path
++ local link=
++ local pfxlen=0
++ for option in '${symdir}*'
++ [[ -e /dev/disk/by-path ]]
+++ readlink -f /dev/disk/by-path//dev/disk/by-path
++ [[ '' == \/\d\e\v\/\s\d\a\2 ]]
++ [[ 0 -eq 0 ]]
++ log 'Could not locate appropriate symlink for partition 2 of /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0'
++ '[' -z 'Could not locate appropriate symlink for partition 2 of /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0' ']'
++ local timestamp
+++ date '+%F %T'
++ timestamp='2017-08-18 20:34:04'
++ echo '2017-08-18 20:34:04  entrypoint.sh: Could not locate appropriate symlink for partition 2 of /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0'
2017-08-18 20:34:04  entrypoint.sh: Could not locate appropriate symlink for partition 2 of /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0
++ return 0
++ exit 1
...
```

### PR DESCRIPTION
**Pull request by BlaineEXE**
Fixes #750 

While investigating this issue, it appears from the git blame of the file, the error was introduced when a dev cleaned up the shellcheck lining errors. I don't want to suggest any blame, and I'm glad to see that people are interested in maintaining clean, maintainable code. This error could have been caught with unit testing, and ideally, I'd like to add unit tests starting with this code. I can see a few ways to proceed, however, and I'd like to discuss the community's interest and thoughts. Here are my thoughts so far:

- With a codebase of scripts this large, it may be more appropriate to convert code to Python and add unit tests for all Python code. Python has strong unit testing and libraries and seems more suitable for a project that is this size and growing larger. This could be done all-at-once, or it could be done incrementally on a by-function or by-file basis as updates/additions to the codebase are needed.
- On the flip side of this argument, there is already a substantial amount of scripting written in bash, and there has been care taken to ensure the scripts are high quality. It could make more sense to instead add bash unit tests to the codebase. This also could be done all-at-once, or it could be done on a function-by-function basis as updates/additions to the codebase are needed.

### CODE REVIEW

**Comment by JrCs** [comment]
Please don't convert code to Python !
If we want to do test units on bash scripts we can use [bats](https://github.com/sstephenson/bats). It's really a great testing system for scripts and it is used in large number of projects.

**Comment by leseb** [comment]
jenkins test sloppy bash

**Comment by leseb** [comment]
jenkins test ceph_ansible-luminous-centos7-cluster

**Comment by leseb** [comment]
jenkins test ceph_ansible-luminous-xenial-cluster

**Comment by leseb** [comment]
One CI issue is the race condition, the other one is fixed here: https://github.com/ceph/ceph-docker/pull/754

**Comment by leseb** [comment]
@BlaineEXE can we have the same contribution for both jewel and kraken?
Thanks!

**Comment by BlaineEXE** [comment]
Is there any reason why these changes can't be added to jewel and kraken by symlinking the file instead of keeping duplicate code?

**Comment by leseb** [comment]
@BlaineEXE The code base is evolving through each release so doing symlinks for some file only is not maintainable. Duplicating code can be considered painful here but at least it's harmless and less prone to confusion.

Thanks for the update.

**Comment by leseb** [comment]
jenkins test this pleaase

**Comment by leseb** [comment]
jenkins test this please

**Comment by BlaineEXE** [comment]
@leseb, I'm not sure if you are asking me to comment with the "jenkins test X" to kick off jenkins tests like you did before or if your comment is another command to the jenkins instance.

**Comment by leseb** [comment]
@BlaineEXE it's not another command, by triggering it I'm asking Jenkins to re-run all the tests. The error is not due to this patch. However I'd like to keep it a little bit open so I can investigate. No worries, your patch will go next week for sure.

Thanks for your patience :)

**Pull request merged**
