### PR TITLE
remove /etc/environment

### PR DESCRIPTION
**Pull request by rubycut**
This directory of file doesn't exist on coreos.

### CODE REVIEW

**Comment by Ulexus** [comment]
Is there a need or reason for this?  I use this statement on all my nodes.

**Comment by rubycut** [comment]
Well, this line breaks service on coreos. It won't start at all because
/etc/environment doesn't exist.

**Comment by Ulexus** [comment]
That's curious; all my hosts are CoreOS.  What version are you running that `/etc/environment` doesn't exist?

Anyway, I wonder if `EnvironmentFile` will take the `-` prefix... something like:
```
EnvironmentFile=-/etc/environment
```

**Comment by Ulexus** [comment]
According to the [documentation](http://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=), it does.  If you wouldn't mind modifying your PR to simply prefix `-` to `/etc/environment`, it should be clean and good.

**Comment by Ulexus** [comment]
PR #73 fixes this issue

**Pull request closed without merging**
