### PR TITLE
entrypoint: ignore pgrep exit code

### LINKED ISSUE #370: OSD entrypoint script exits when pgrep fails
I'm trying to get some OSDs up and running on CoreOS. They fail when I try to run `activate` and I believe the `entrypoint.sh` script has a small bug.

```
Sep 06 08:33:41 test-storage-001 docker[15543]: create-or-move updated item name 'osd.0' weight 0.01 at location {host=test-storage-001,root=default} to crush map
Sep 06 08:33:41 test-storage-001 systemd[1]: ceph-osd.service: Main process exited, code=exited, status=1/FAILURE
```

https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh#L556

When the entrypoint script reaches that line it is aborting, I assume because `pgrep` exits with status 1 when there are no result.

```
root@test-storage-001:/# pgrep -U ceph -f "^/usr/bin/ceph-osd \-\-cluster ceph.*\-i 0 \-\-setuser"
root@test-storage-001:/# echo $?
1
```

When I patch in a hacked script that skips the check and just runs the `else` case, the OSD starts as expected.

### PR DESCRIPTION
**Pull request by immesys**
pgrep can exit 1 if no results are found

This should fix #370

### CODE REVIEW

**Comment by immesys** [comment]
I am busy testing this now. Will report when I am done

**Comment by immesys** [comment]
I reproduced #370 and with this applied, it now works. Sorry everyone.

**Comment by linuxwind** [comment]
+1

**Comment by leseb** [comment]
Thanks @immesys

**Pull request merged**
