### PR TITLE
tests: update requirements file

### PR DESCRIPTION
**Pull request by font**
Signed-off-by: Ivan Font <ifont@redhat.com>

### CODE REVIEW

**Comment by font** [comment]
@alfredodeza Please take a look. I've updated in order to install all required dependencies to reproduce some of the issues filed.

**Comment by ktdreyer** [comment]
This hard-codes a lot of version numbers, which has caused trouble for other projects in the past (see s3tests or teuthology). What were the specific libs you needed?

**Comment by font** [comment]
Fair enough. I've updated the PR to include only the libs without versions and without its dependencies.

**Comment by alfredodeza** [comment]
@font this is really odd. You mentioned some issues were filed but I couldn't find anything related to this PR. Mind listing them here?

Nothing other than py.test and docker-py is needed. We don't use anything else. `virtualenv` could be just used from the distro directly and not meant to install from a requirements file.

**Comment by font** [comment]
I am no longer running into any module dependency issues. I am closing this PR. Thanks!

**Pull request closed without merging**
